PN-7058: Improve Dashboard and define alarms for Ses and SMS
pagopa/pn-data-vault pull request #120
Opened 2023-09-26 21:50 UTC by mbrachi

2023-09-27 06:41 UTC, fdammassa requested changes
@mbrachi ti ho fatto alcune richieste di modifica ed una domanda sulla Statistica utilizzata.

Inoltre, volevo chiederti di quanto le soglie impostate sono più basse del massimo imposto da AWS.

2023-09-27 06:41 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +        Statistic: Average
@mbrachi dato che dobbiamo verificare una soglia, è corretto usare Average ? forse una statistica come Max o Sum potrebbe essere più corretta?

2023-09-27 06:41 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +        Threshold: 800000
@mbrachi rendilo parametrico così con 800000 di default, così se dobbiamo cambiare le soglie non si deve fare un deploy di data-vault

2023-09-27 06:41 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +        Threshold: 24000
@mbrachi rendilo parametrico così con 24000 di default, così se dobbiamo cambiare le soglie non si deve fare un deploy di data-vault

2023-09-27 06:41 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +        InsufficientDataActions:
@mbrachi elimina questa azione

2023-09-27 06:41 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +        InsufficientDataActions:
@mbrachi elimina questa azione

2023-09-28 17:37 UTC, mbrachi commented on scripts/aws/cfn/infra.yml
> +        Statistic: Average
Impostata su Maximum.

2023-09-29 07:08 UTC, fdammassa requested changes

2023-09-29 07:08 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +    Type: Double
@mbrachi puoi usare "Number" qui ?

2023-09-29 07:08 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +    Type: Double
@mbrachi puoi usare "Number" qui ?

2023-09-29 07:08 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +        TreatMissingData: missing
@mbrachi usa "notBreaching"

2023-09-29 07:08 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +      RetentionInDays: 7
@mbrachi lo rendiamo parametrico?

2023-09-29 07:08 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +      Timeout: 7
@mbrachi mettiamo anche a 30 secondi, metti che c'è un pò di latenza di rete in quel momento

2023-09-29 07:08 UTC, fdammassa commented on scripts/aws/cfn/infra.yml
> +                      'MetricName': 'MailSentLast24Hours',
@mbrachi non sarebbe più corretto pubblicare la percentuale d'utilizzo? la get_send_quota ti dà anche il limite quindi puoi calcolarti la percentuale. Piuttosto che passartela come parametro. Su questo parliamone a voce.

2023-09-29 13:10 UTC, fdammassa approved these changes

2023-10-09 13:33 UTC, merged